# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI E2E build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Update and firewall stop
        run: |
          sudo apt update
          sudo systemctl stop ufw
          sudo apt install -y iproute2
          sudo apt install git curl hey
          ip a
          ping 127.0.0.1 -c 2
          sudo apt install net-tools
          netstat -anpe | grep 49280
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: Tests
        run: |
          sudo cp -r /home/runner/work/l3afd/l3afd /root
          sudo git clone -b vm-test https://github.com/Atul-source/l3af-arch.git /root/l3af-arch
          sudo bash /root/l3af-arch/dev_environment/e2e_test/prep.sh
          sudo bash /root/l3af-arch/dev_environment/e2e_test/setup_linux_dev_env.sh
          hm=$(hostname)
          sudo find /root/l3af-arch/dev_environment/e2e_test -type f -name "*.json" -exec sed -i "s/lima-bpfdev/$hm/g" {} +
          sudo bash /root/l3af-arch/dev_environment/e2e_test/test_suite.sh
