name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 240
    steps:
      - name: brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: lima install
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_on: error
          command: |
            brew install lima
            limactl start --name=default --cpus=4 --memory=8 --vm-type=vz --rosetta --mount-writable --network=vzNAT template://ubuntu-lts
            lima uname -a
