# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI E2E build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: prep
        run: |
          sudo apt update
          sudo systemctl stop ufw
          sudo apt install net-tools
          sudo apt-get install uml-utilities
          sudo ip tuntap add dev eth1 mode tun
          sudo ip addr add 10.1.10.1/24 dev eth1
          sudo ip link set dev eth1 up

      - name: tf-prep
        run: |
          IP=$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
          sudo modprobe fou
          sudo ip fou add port 6080 gue
          sudo ip link add name gue1 type ipip remote 10.1.10.1 local $IP ttl 255 encap gue encap-sport 6080 encap-dport 6081 encap-csum encap-remcsum
          sudo ip link set dev gue1 up
          sudo ip fou add port 6081 gue
          sudo ip link add name gue2 type ipip remote $IP local 10.1.10.1  ttl 255 encap gue encap-sport 6081 encap-dport 6080 encap-csum encap-remcsum
          sudo ip link set dev gue2 up

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: clone
        run: |
          sudo cp -r /home/runner/work/l3afd/l3afd /root
          sudo apt-get install git
          sudo git clone -b E2E https://github.com/Atul-source/l3af-arch.git /root/l3af-arch
          sudo su
          cd /root/l3af-arch/dev_environment/e2e_test
          ./setup_linux_dev_env.sh
          ps -ef | grep -i l3af

          

