name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 280
    steps:
      - name: brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: clone
        run: |
          brew install --cask virtualbox
          brew install --cask vagrant
          vagrant plugin install vagrant-vbguest
          vagrant init ubuntu/focal64
          vagrant up
          vagrant ssh -c 'lsb_release -a'

