name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 280
    steps:
      - name: brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: clone
        run: |
          brew install --cask virtualbox
          brew install --cask vagrant
          vagrant plugin install vagrant-reload
          git clone https://github.com/l3af-project/l3af-arch.git
          cd l3af-arch/dev_environment
          vagrant up
          vagrant ssh l3af -c "lsb_release -a"
