name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Homebrew
      run: |
        sudo apt-get install build-essential curl file git
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    
    - name: check
      run: |
        brew doctor
